name: Turbo Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Windows App
        run: |
          go mod tidy
          go build -o FreeFast_Win.exe .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Build
          path: FreeFast_Win.exe
